export const HYDRATE_CONFIG_PROFILES = 'HYDRATE_CONFIG_PROFILES';
export const CLEAR_ACTIVE_CONFIG_PROFILE = 'CLEAR_ACTIVE_CONFIG_PROFILE';
export const SET_ACTIVE_CONFIG_PROFILE = 'SET_ACTIVE_CONFIG_PROFILE';

/** UI / saga intents */
export const LOAD_CONFIG_PROFILES = 'LOAD_CONFIG_PROFILES';
export const SAVE_CONFIG_PROFILE_AS = 'SAVE_CONFIG_PROFILE_AS';
export const SAVE_ACTIVE_CONFIG_PROFILE = 'SAVE_ACTIVE_CONFIG_PROFILE';
export const SWITCH_CONFIG_PROFILE = 'SWITCH_CONFIG_PROFILE';
export const RENAME_CONFIG_PROFILE = 'RENAME_CONFIG_PROFILE';
export const DELETE_CONFIG_PROFILE = 'DELETE_CONFIG_PROFILE';
export const EXPORT_CURRENT_CONFIG_PROFILE = 'EXPORT_CURRENT_CONFIG_PROFILE';
export const EXPORT_SELECTED_CONFIG_PROFILES = 'EXPORT_SELECTED_CONFIG_PROFILES';
export const IMPORT_CONFIG_PROFILES = 'IMPORT_CONFIG_PROFILES';
