export const START_CONFIG_SAGA = "START_CONFIG_SAGA";
export const STOP_CONFIG_SAGA = "STOP_CONFIG_SAGA";

export const UPDATE_CONFIG = "UPDATE_CONFIG";

export const CHANGE_SUFFIX = 'CHANGE_SUFFIX';
export const CHANGE_PREFIX = 'CHANGE_PREFIX';
export const TOGGLE_UUID = 'TOGGLE_UUID';
export const TOGGLE_PREFIX = 'TOGGLE_PREFIX';
export const TOGGLE_SUFFIX = 'TOGGLE_SUFFIX';
export const TOGGLE_NON_RANDOM = 'TOGGLE_NON_RANDOM';
export const TURN_ON_RENAME_MODE = 'TURN_ON_RENAME_MODE';

export const TOGGLE_SAVE_CSV = 'TOGGLE_SAVE_CSV';
export const CHANGE_FILE_PATH_COLUMN = "CHANGE_FILE_PATH_COLUMN";
export const CHANGE_FILE_RENAME_COLUMN = "CHANGE_FILE_RENAME_COLUMN";
export const CHANGE_FILE_DESTINATION_DIRECTORY_COLUMN = "CHANGE_FILE_DESTINATION_DIRECTORY_COLUMN";

export const TOGGLE_SAVE_MACRO = "TOGGLE_SAVE_MACRO";
export const TOGGLE_ADD_LABEL_QR = "TOGGLE_ADD_QR";
export const TOGGLE_ADD_LABEL_TEXT = "TOGGLE_ADD_TEXT";
export const TOGGLE_ADD_ICON = "TOGGLE_ADD_ICON";

export const CHANGE_QR_MODE = 'CHANGE_QR_MODE';
export const CHANGE_QR_COLUMN_FIELDS = 'CHANGE_QR_COLUMN_FIELDS';
export const CHANGE_QR_COLUMN_FIELD = 'CHANGE_QR_COLUMN_FIELD';
export const CHANGE_TEXT_COLUMN_FIELD = 'CHANGE_TEXT_COLUMN_FIELD';
export const CHANGE_ICON_FILE = "CHANGE_ICON_FILE";
export const SELECT_ICON_FILE = "SELECT_ICON_FILE";

export const TOGGLE_ENABLE_DEBUG = "TOGGLE_ENABLE_DEBUG";


