export const START_CONFIG_SAGA = "START_CONFIG_SAGA";
export const STOP_CONFIG_SAGA = "STOP_CONFIG_SAGA";

export const UPDATE_CONFIG = "UPDATE_CONFIG";

export const TOGGLE_UUID = 'TOGGLE_UUID';
export const TOGGLE_NON_RANDOM = 'TOGGLE_NON_RANDOM';
export const TURN_ON_RENAME_MODE = 'TURN_ON_RENAME_MODE';

export const TOGGLE_SAVE_CSV = 'TOGGLE_SAVE_CSV';
export const CHANGE_FILE_PATH_COLUMN = "CHANGE_FILE_PATH_COLUMN";
export const CHANGE_FILE_RENAME_COLUMN = "CHANGE_FILE_RENAME_COLUMN";
export const CHANGE_FILE_DESTINATION_DIRECTORY_COLUMN = "CHANGE_FILE_DESTINATION_DIRECTORY_COLUMN";

export const TOGGLE_SAVE_MACRO = "TOGGLE_SAVE_MACRO";
export const TOGGLE_ADD_LABEL_QR = "TOGGLE_ADD_QR";
export const TOGGLE_ADD_LABEL_TEXT = "TOGGLE_ADD_TEXT";
export const TOGGLE_ADD_ICON = "TOGGLE_ADD_ICON";

export const CHANGE_QR_MODE = 'CHANGE_QR_MODE';
export const CHANGE_QR_COLUMN_FIELDS = 'CHANGE_QR_COLUMN_FIELDS';
export const CHANGE_QR_COLUMN_FIELD = 'CHANGE_QR_COLUMN_FIELD';
export const CHANGE_TEXT_COLUMN_FIELD = 'CHANGE_TEXT_COLUMN_FIELD';
export const CHANGE_ICON_FILE = "CHANGE_ICON_FILE";
export const SELECT_ICON_FILE = "SELECT_ICON_FILE";

export const TOGGLE_ENABLE_DEBUG = "TOGGLE_ENABLE_DEBUG";
export const TOGGLE_ENABLE_COPY_MODE = "TOGGLE_ENABLE_COPY_MODE";

export const EXPORT_SAMPLE_CSV_TEMPLATE = "EXPORT_SAMPLE_CSV_TEMPLATE";

export const SET_NAMING_CONFIG = 'SET_NAMING_CONFIG';
export const SET_LABEL_TEXT_ASSEMBLY = 'SET_LABEL_TEXT_ASSEMBLY';
export const SET_QR_ASSEMBLY = 'SET_QR_ASSEMBLY';
export const SET_DSA_UPLOAD_CONFIG = 'SET_DSA_UPLOAD_CONFIG';
export const RECOMPUTE_ALL_NAMING = 'RECOMPUTE_ALL_NAMING';

export const SET_FILENAME_CONFIG = 'SET_FILENAME_CONFIG';
export const SET_ASSEMBLY_CONFIG = 'SET_ASSEMBLY_CONFIG';
export const SET_ROUTING_CONFIG = 'SET_ROUTING_CONFIG';
export const SET_LABEL_DEFAULTS = 'SET_LABEL_DEFAULTS';
export const USE_ASSEMBLED_NAME_FOR_LABEL = 'USE_ASSEMBLED_NAME_FOR_LABEL';