export const SET_HAS_ERROR = 'SET_HAS_ERROR';
export const CLEAR_HAS_ERROR = 'CLEAR_HAS_ERROR';
export const ADD_FRONTEND_ERROR_MESSAGE = 'ADD_FRONTEND_ERROR_MESSAGE';
export const ADD_BACKEND_ERROR_MESSAGE = 'ADD_BACKEND_ERROR_MESSAGE';
export const CLEAR_FRONTEND_ERROR_MESSAGES = 'CLEAR_FRONTEND_ERROR_MESSAGES';
export const CLEAR_BACKEND_ERROR_MESSAGES = 'CLEAR_BACKEND_ERROR_MESSAGES';
export const SET_DISPLAY_DEBUG = 'SET_DISPLAY_DEBUG';
export const CLEAR_DISPLAY_DEBUG = 'CLEAR_DISPLAY_DEBUG';
export const ADD_FRONTEND_DEBUG_MESSAGE = 'ADD_FRONTEND_DEBUG_MESSAGE';
export const ADD_BACKEND_DEBUG_MESSAGE = 'ADD_BACKEND_DEBUG_MESSAGE';
export const CLEAR_FRONTEND_DEBUG_MESSAGES = 'CLEAR_FRONTEND_DEBUG_MESSAGES';
export const CLEAR_BACKEND_DEBUG_MESSAGES = 'CLEAR_BACKEND_DEBUG_MESSAGES';

export const SET_BACKEND_ERROR_MESSAGES = 'SET_BACKEND_ERROR_MESSAGES';
export const SET_BACKEND_DEBUG_MESSAGES = 'SET_BACKEND_DEBUG_MESSAGES';
export const GET_BACKEND_ERROR_MESSAGES = 'GET_BACKEND_ERROR_MESSAGES';
export const GET_BACKEND_DEBUG_MESSAGES = 'GET_BACKEND_DEBUG_MESSAGES';

export const START_DEBUG_SAGA = 'START_DEBUG_SAGA';
export const STOP_DEBUG_SAGA = 'STOP_DEBUG_SAGA';

export const EXPORT_DEBUG_JSON = 'EXPORT_DEBUG_JSON';