export const LOGIN_SUCCESS = 'dsa/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'dsa/LOGIN_FAILURE';
export const SET_DSA_API_URL = 'dsa/SET_DSA_API_URL';
export const SET_DSA_USERNAME = 'dsa/SET_DSA_USERNAME';
export const SET_DSA_PASSWORD = 'dsa/SET_DSA_PASSWORD';
export const LOGIN = 'dsa/LOGIN';
export const LOGOUT = 'dsa/LOGOUT';
export const LOGOUT_SUCCESS = 'dsa/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'dsa/LOGOUT_FAILURE';
export const UPLOAD_FILE = 'dsa/UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'dsa/UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_COMPLETE = 'dsa/UPLOAD_FILE_COMPLETE';
export const UPDATE_UPLOAD_STATUS = 'dsa/UPDATE_UPLOAD_STATUS';
export const UPLOAD_FILE_FAILURE = 'dsa/UPLOAD_FILE_FAILURE';
export const UPLOAD_FILE_FINALIZE = 'dsa/UPLOAD_FILE_FINALIZE';
export const ADD_UPLOAD_FILE_TO_QUEUE = 'dsa/ADD_UPLOAD_FILE_TO_QUEUE';
export const REMOVE_UPLOAD_FILE_FROM_QUEUE = 'dsa/REMOVE_UPLOAD_FILE_FROM_QUEUE';
export const SET_UPLOADING = 'dsa/SET_UPLOADING';

export const TOGGLE_UPLOAD_TO_DSA = 'dsa/TOGGLE_UPLOAD_TO_DSA';
export const TOGGLE_DELETE_AFTER_DSA_UPLOAD = 'dsa/TOGGLE_DELETE_AFTER_DSA_UPLOAD';
export const SET_DSA_FOLDER_ID = 'dsa/SET_DSA_FOLDER_ID';
export const SET_DSA_UPLOAD_THROTTLE_LIMIT = 'dsa/SET_DSA_UPLOAD_THROTTLE_LIMIT';
export const DSA_FOLDER_EXISTS = 'dsa/DSA_FOLDER_EXISTS';
export const DSA_FOLDER_DOES_NOT_EXIST = 'dsa/DSA_FOLDER_DOES_NOT_EXIST';

// Persistence
export const UPDATE_DSA = 'dsa/UPDATE_DSA';
