export const SET_ESM_USERNAME = 'SET_ESM_USERNAME';
export const SET_ESM_PASSWORD = 'SET_ESM_PASSWORD';
export const SET_ESM_INTEGRATION_ENABLED = 'SET_ESM_INTEGRATION_ENABLED';
export const SET_ESM_REMEMBER_USERNAME = 'SET_ESM_REMEMBER_USERNAME';
export const ESM_LOGIN = 'ESM_LOGIN';
export const ESM_LOGIN_SUCCESS = 'ESM_LOGIN_SUCCESS';
export const ESM_LOGIN_ERROR = 'ESM_LOGIN_ERROR';
export const ESM_LOGOUT = 'ESM_LOGOUT';
export const ESM_LOGOUT_SUCCESS = 'ESM_LOGOUT_SUCCESS';
// Search criteria rows (accession / optional de-ID / optional stain)
export const ESM_SET_SEARCH_ROWS = 'ESM_SET_SEARCH_ROWS';
export const ESM_ADD_SEARCH_ROW = 'ESM_ADD_SEARCH_ROW';
export const ESM_UPDATE_SEARCH_ROW = 'ESM_UPDATE_SEARCH_ROW';
export const ESM_REMOVE_SEARCH_ROW = 'ESM_REMOVE_SEARCH_ROW';

export const ESM_SEARCH = 'ESM_SEARCH';
export const ESM_SEARCH_BATCH = 'ESM_SEARCH_BATCH';
export const ESM_SEARCH_SUCCESS = 'ESM_SEARCH_SUCCESS';
export const ESM_SEARCH_ERROR = 'ESM_SEARCH_ERROR';
export const ESM_SEARCH_COMPLETE = 'ESM_SEARCH_COMPLETE';
export const ESM_SET_LOADING = 'ESM_SET_LOADING';

// Results + selection
export const ESM_SET_RESULTS = 'ESM_SET_RESULTS';
export const ESM_SET_SLIDES_BY_ACCESSION = 'ESM_SET_SLIDES_BY_ACCESSION';
export const ESM_CLEAR_RESULTS = 'ESM_CLEAR_RESULTS';
export const ESM_SET_SELECTION = 'ESM_SET_SELECTION';

// Profiles
export const ESM_SET_ACTIVE_PROFILE_ID = 'ESM_SET_ACTIVE_PROFILE_ID';
export const ESM_ADD_PROFILE = 'ESM_ADD_PROFILE';
export const ESM_UPDATE_PROFILE = 'ESM_UPDATE_PROFILE';
export const ESM_DELETE_PROFILE = 'ESM_DELETE_PROFILE';

// Transform rules (per profile)
export const ESM_ADD_TRANSFORM_RULE = 'ESM_ADD_TRANSFORM_RULE';
export const ESM_UPDATE_TRANSFORM_RULE = 'ESM_UPDATE_TRANSFORM_RULE';
export const ESM_DELETE_TRANSFORM_RULE = 'ESM_DELETE_TRANSFORM_RULE';

// Apply selected search results into main file list
export const ESM_APPLY_SELECTION = 'ESM_APPLY_SELECTION';

// Persistence
export const UPDATE_ESM = 'UPDATE_ESM';

// Legacy — kept for migration only
export const SET_ESM_URL = 'SET_ESM_URL';
export const ESM_SET_MAPPING_CONFIG = 'ESM_SET_MAPPING_CONFIG';
export const ESM_SET_SELECTED_TRANSFORM_RULE_IDS = 'ESM_SET_SELECTED_TRANSFORM_RULE_IDS';
