export const UPDATE_FILES = "UPDATE_FILES";

export const START_FILES_SAGA = "START_FILES_SAGA";
export const STOP_FILES_SAGA = "STOP_FILES_SAGA";

export const ADD_FILES = "ADD_FILES";
export const ADD_FOLDER = "ADD_FOLDER";
export const ADD_FOLDERS = "ADD_FOLDERS";
export const CHOOSE_OUTPUT_DIR = "CHOOSE_OUTPUT_DIR";
export const CHOOSE_CSV_OUTPUT_DIR = "CHOOSE_CSV_OUTPUT_DIR";
export const CHOOSE_INPUT_DIR = "CHOOSE_INPUT_DIR";
export const CLEAR_FILES = "CLEAR_FILES";
export const REMOVE_FILE = "REMOVE_FILE";
export const UPDATE_FILE_PROGRESS = "UPDATE_FILE_PROGRESS";
export const CLEAR_PROGRESS = "CLEAR_PROGRESS";
export const PROCESSED_FILE = "PROCESSED_FILE";
export const CLEAR_PROCESSING_FILES = "CLEAR_PROCESSING_FILES";
export const RESET_FILE_ROW_PROGRESS = "RESET_FILE_ROW_PROGRESS";

export const ADD_FILE_ROW = "ADD_FILE_ROW";
export const ADD_FILE_ROWS = "ADD_FILE_ROWS";
export const UPDATE_FILE_ROW_WITH_METADATA =  "UPDATE_FILE_ROW_WITH_METADATA";
export const REMOVE_FILE_ROW = "REMOVE_FILE_ROW";
export const ADD_FILE_COL = "ADD_FILE_COL";
export const UPDATE_FILE_ROW_WITHOUT_METADATA =  "UPDATE_FILE_ROW_WITHOUT_METADATA";
export const UPDATE_ROW = "UPDATE_ROW";
export const UPDATE_FILES_WITHOUT_METADATA = "UPDATE_FILES_WITHOUT_METADATA";
export const SET_METADATA_UPDATING = "SET_METADATA_UPDATING";
export const UPDATE_FILE_ROW_WITH_ERROR = "UPDATE_FILE_ROW_WITH_ERROR";

export const SET_OUTPUT_DIR = "SET_OUTPUT_DIR";
export const SET_INPUT_DIR = "SET_INPUT_DIR";

export const OPEN_VIEWER = "OPEN_VIEWER";

export const GET_METADATA = "GET_METADATA";
export const GET_COPY_PROGRESS = "GET_COPY_PROGRESS";
export const PROCESS_FILE = "PROCESS_FILE";
export const PROCESS_FILES = "PROCESS_FILES";
export const TOGGLE_PROCESSING = "TOGGLE_PROCESSING";
export const TOGGLE_PROCESSED = "TOGGLE_PROCESSED";
export const ADD_PROCESSING_FILE = "ADD_PROCESSING_FILE";
export const REMOVE_PROCESSING_FILE = "REMOVE_PROCESSING_FILE";
export const CANCEL_PROCESS_FILES = "CANCEL_PROCESS_FILES";
export const PROCESS_FILE_ERROR = "PROCESS_FILE_ERROR";
export const NOT_PROCESSING = "NOT_PROCESSING";

export const ADD_TOTAL_BYTES = "ADD_TOTAL_BYTES";
export const REMOVE_TOTAL_BYTES = "REMOVE_TOTAL_BYTES";

export const SET_CSV_FILE = "SET_CSV_FILE";
export const ADD_CSV = "ADD_CSV";
export const SELECT_IMPORT_CSV_XSLX = "SELECT_IMPORT_CSV_XSLX";
export const SELECT_OUTPUT_CSV_XSLX = "SELECT_OUTPUT_CSV_XSLX";
export const ADD_CSV_HEADERS = "ADD_CSV_HEADERS";
export const SET_CSV_FILE_PATH = "SET_CSV_FILE_PATH";
export const ADD_CSV_ROWS = "ADD_CSV_ROWS";
export const LINK_CSV_HEADER = "LINK_CSV_HEADER";
export const CSV_IMPORT_COMPLETE = "CSV_IMPORT_COMPLETE";
export const SET_CSV_NEEDS_CSV_OUTPUT_DIR = "SET_CSV_NEEDS_CSV_OUTPUT_DIR";
export const SET_CSV_OUTPUT_DIR = "SET_CSV_OUTPUT_DIR";
export const SET_CSV_NEEDS_OUTPUT_DIR = "SET_CSV_NEEDS_OUTPUT_DIR";

export const DISABLE_CHANGES = "DISABLE_CHANGES";
export const ENABLE_CHANGES = "ENABLE_CHANGES";

export const LINK_HEADER_TO_PATH_COLUMN = "LINK_HEADER_TO_PATH_COLUMN";
export const LINK_HEADER_TO_RENAME_COLUMN = "LINK_HEADER_TO_RENAME_COLUMN";
export const LINK_HEADER_TO_DESTINATION_DIRECTORY_COLUMN = "LINK_HEADER_TO_DESTINATION_DIRECTORY_COLUMN";
