export const UPDATE_MODAL = "UPDATE_MODAL";
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';

export const DISPLAY_WARNING_MESSAGE = 'DISPLAY_WARNING_MESSAGE';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const DISALLOW_SELECT_CSV = 'DISALLOW_SELECT_CSV';
export const ALLOW_SELECT_CSV_PATH_COLUMN = 'ALLOW_SELECT_CSV_PATH_COLUMN';
export const ALLOW_SELECT_CSV_RENAME_COLUMN = 'ALLOW_SELECT_CSV_RENAME_COLUMN';
export const ALLOW_SELECT_CSV_DESTINATION_DIRECTORY_COLUMN = 'ALLOW_SELECT_CSV_DESTINATION_DIRECTORY_COLUMN';