# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.proto import engine_pb2 as src_dot_proto_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/proto/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
                '/engine.EngineService/GetMetadata',
                request_serializer=src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.MetadataReply.FromString,
                _registered_method=True)
        self.GetThumbnail = channel.unary_unary(
                '/engine.EngineService/GetThumbnail',
                request_serializer=src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.GetLabel = channel.unary_unary(
                '/engine.EngineService/GetLabel',
                request_serializer=src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.GetMacro = channel.unary_unary(
                '/engine.EngineService/GetMacro',
                request_serializer=src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.GetAssociatedImage = channel.unary_unary(
                '/engine.EngineService/GetAssociatedImage',
                request_serializer=src_dot_proto_dot_engine__pb2.AssociatedImageRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.GetTile = channel.unary_unary(
                '/engine.EngineService/GetTile',
                request_serializer=src_dot_proto_dot_engine__pb2.TileRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.PreviewLabel = channel.unary_unary(
                '/engine.EngineService/PreviewLabel',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.PreviewMacro = channel.unary_unary(
                '/engine.EngineService/PreviewMacro',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ImageReply.FromString,
                _registered_method=True)
        self.PreviewMetadata = channel.unary_unary(
                '/engine.EngineService/PreviewMetadata',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.PreviewMetadataReply.FromString,
                _registered_method=True)
        self.DeidProcess = channel.unary_unary(
                '/engine.EngineService/DeidProcess',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.StructReply.FromString,
                _registered_method=True)
        self.GetOutputPath = channel.unary_unary(
                '/engine.EngineService/GetOutputPath',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.StringReply.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/engine.EngineService/GetProgress',
                request_serializer=src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.ProgressReply.FromString,
                _registered_method=True)
        self.GetErrors = channel.unary_unary(
                '/engine.EngineService/GetErrors',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.StringListReply.FromString,
                _registered_method=True)
        self.ClearErrors = channel.unary_unary(
                '/engine.EngineService/ClearErrors',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDebugs = channel.unary_unary(
                '/engine.EngineService/GetDebugs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_proto_dot_engine__pb2.StringListReply.FromString,
                _registered_method=True)
        self.ClearDebugs = channel.unary_unary(
                '/engine.EngineService/ClearDebugs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMetadata(self, request, context):
        """---- WSI / images ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThumbnail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMacro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssociatedImage(self, request, context):
        """arbitrary associated image by name ("label", "macro", etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewLabel(self, request, context):
        """---- DeidTools preview ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewMacro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeidProcess(self, request, context):
        """---- DeidTools workflow ----
        DeidReply = Struct
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutputPath(self, request, context):
        """---- Utilities / diagnostics ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """typed; you’ll refine later
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDebugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearDebugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=src_dot_proto_dot_engine__pb2.FileRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.MetadataReply.SerializeToString,
            ),
            'GetThumbnail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThumbnail,
                    request_deserializer=src_dot_proto_dot_engine__pb2.FileRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'GetLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLabel,
                    request_deserializer=src_dot_proto_dot_engine__pb2.FileRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'GetMacro': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMacro,
                    request_deserializer=src_dot_proto_dot_engine__pb2.FileRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'GetAssociatedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssociatedImage,
                    request_deserializer=src_dot_proto_dot_engine__pb2.AssociatedImageRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'GetTile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTile,
                    request_deserializer=src_dot_proto_dot_engine__pb2.TileRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'PreviewLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewLabel,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'PreviewMacro': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewMacro,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ImageReply.SerializeToString,
            ),
            'PreviewMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewMetadata,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.PreviewMetadataReply.SerializeToString,
            ),
            'DeidProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeidProcess,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.StructReply.SerializeToString,
            ),
            'GetOutputPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutputPath,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.StringReply.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=src_dot_proto_dot_engine__pb2.StructRequest.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.ProgressReply.SerializeToString,
            ),
            'GetErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrors,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.StringListReply.SerializeToString,
            ),
            'ClearErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearErrors,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDebugs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDebugs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_proto_dot_engine__pb2.StringListReply.SerializeToString,
            ),
            'ClearDebugs': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearDebugs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetMetadata',
            src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.MetadataReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThumbnail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetThumbnail',
            src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetLabel',
            src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMacro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetMacro',
            src_dot_proto_dot_engine__pb2.FileRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssociatedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetAssociatedImage',
            src_dot_proto_dot_engine__pb2.AssociatedImageRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetTile',
            src_dot_proto_dot_engine__pb2.TileRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/PreviewLabel',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewMacro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/PreviewMacro',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ImageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/PreviewMetadata',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.PreviewMetadataReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeidProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/DeidProcess',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.StructReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutputPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetOutputPath',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.StringReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetProgress',
            src_dot_proto_dot_engine__pb2.StructRequest.SerializeToString,
            src_dot_proto_dot_engine__pb2.ProgressReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetErrors',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_proto_dot_engine__pb2.StringListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/ClearErrors',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDebugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetDebugs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_proto_dot_engine__pb2.StringListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearDebugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/ClearDebugs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
